//SignIn
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCSS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

//SignUp
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

//ForgotPassword
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

//ResetPassword
export const RESET_PASSWORD_REQUEST = "REQUEST_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "REQUEST_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "REQUEST_PASSWORD_ERROR";

//Customer Name
export const CUSTOMER_NAME_REQUEST = "CUSTOMER_NAME_REQUEST";
export const CUSTOMER_NAME_SUCCESS = "CUSTOMER_NAME_SUCCESS";
export const CUSTOMER_NAME_ERROR = "CUSTOMER_NAME_ERROR";

//Customer Profile
export const CUSTOMER_PROFILE_REQUEST = "CUSTOMER_PROFILE_REQUEST";
export const CUSTOMER_PROFILE_SUCCESS = "CUSTOMER_PROFILE_SUCCESS";
export const CUSTOMER_PROFILE_ERROR = "CUSTOMER_PROFILE_ERROR";
export const CUSTOMER_PROFILE_EDIT_REQUEST = "CUSTOMER_PROFILE_EDIT_REQUEST";
export const CUSTOMER_PROFILE_EDIT_SUCCESS = "CUSTOMER_PROFILE_EDIT_SUCCESS";
export const CUSTOMER_PROFILE_EDIT_ERROR = "CUSTOMER_PROFILE_EDIT_ERROR";

//Customer Notification Count
export const CUSTOMER_NOTIFICATION_COUNT_REQUEST =
  "CUSTOMER_NOTIFICATION_COUNT_REQUEST";
export const CUSTOMER_NOTIFICATION_COUNT_SUCCESS =
  "CUSTOMER_NOTIFICATION_COUNT_SUCCESS";
export const CUSTOMER_NOTIFICATION_COUNT_ERROR =
  "CUSTOMER_NOTIFICATION_COUNT_ERROR";

//Customer Notification Data
export const CUSTOMER_NOTIFICATION_DATA_REQUEST =
  "CUSTOMER_NOTIFICATION_DATA_REQUEST";
export const CUSTOMER_NOTIFICATION_DATA_SUCCESS =
  "CUSTOMER_NOTIFICATION_DATA_SUCCESS";
export const CUSTOMER_NOTIFICATION_DATA_ERROR =
  "CUSTOMER_NOTIFICATION_DATA_ERROR";

//Customer PickUp
export const CUSTOMER_PICKUP_REQUEST = "CUSTOMER_PICKUP_REQUEST";
export const CUSTOMER_PICKUP_SUCCESS = "CUSTOMER_PICKUP_SUCCESS";
export const CUSTOMER_PICKUP_ERROR = "CUSTOMER_PICKUP_ERROR";
export const CUSTOMER_COUNT_COLL_REQUEST = "CUSTOMER_COUNT_COLL_REQUEST";
export const CUSTOMER_COUNT_COLL_SUCCESS = "CUSTOMER_COUNT_COLL_SUCCESS";
export const CUSTOMER_COUNT_COLL_ERROR = "CUSTOMER_COUNT_COLL_ERROR";

//Customer DropOff
export const CUSTOMER_DROPOFF_REQUEST = "CUSTOMER_DROPOFF_REQUEST";
export const CUSTOMER_DROPOFF_SUCCESS = "CUSTOMER_DROPOFF_SUCCESS";
export const CUSTOMER_DROPOFF_ERROR = "CUSTOMER_DROPOFF_ERROR";
export const CUSTOMER_VIEW_COLLECTORS_REQUEST =
  "CUSTOMER_VIEW_COLLECTORS_REQUEST";
export const CUSTOMER_VIEW_COLLECTORS_SUCCESS =
  "CUSTOMER_VIEW_COLLECTORS_SUCCESS";
export const CUSTOMER_VIEW_COLLECTORS_ERROR = "CUSTOMER_VIEW_COLLECTORS_ERROR";

//Customer Pending Request
export const CUSTOMER_PENDING_REQUEST = "CUSTOMER_PENDING_REQUEST";
export const CUSTOMER_PENDING_SUCCESS = "CUSTOMER_PENDING_SUCCESS";
export const CUSTOMER_PENDING_ERROR = "CUSTOMER_PENDING_ERROR";

//Customer Expired Request
export const CUSTOMER_EXPIRED_REQUEST = "CUSTOMER_EXPIRED_REQUEST";
export const CUSTOMER_EXPIRED_SUCCESS = "CUSTOMER_EXPIRED_SUCCESS";
export const CUSTOMER_EXPIRED_ERROR = "CUSTOMER_EXPIRED_ERROR";

//Customer Completed Request
export const CUSTOMER_COMPLETED_REQUEST = "CUSTOMER_COMPLETED_REQUEST";
export const CUSTOMER_COMPLETED_SUCCESS = "CUSTOMER_COMPLETED_SUCCESS";
export const CUSTOMER_COMPLETED_ERROR = "CUSTOMER_COMPLETED_ERROR";

//Customer E-Waste Drives
export const CUSTOMER_EWASTE_DRIVES_REQUEST = "CUSTOMER_EWASTE_DRIVES_REQUEST";
export const CUSTOMER_EWASTE_DRIVES_SUCCESS = "CUSTOMER_EWASTE_DRIVES_SUCCESS";
export const CUSTOMER_EWASTE_DRIVES_ERROR = "CUSTOMER_EWASTE_DRIVES_ERROR";

//Customer Analytics
export const CUSTOMER_DRIVES_REQUEST = "CUSTOMER_DRIVES_REQUEST";
export const CUSTOMER_DRIVES_SUCCESS = "CUSTOMER_DRIVES_SUCCESS";
export const CUSTOMER_DRIVES_ERROR = "CUSTOMER_DRIVES_ERROR";
export const CUSTOMER_COLLECTORCATEGORIES_REQUEST =
  "CUSTOMER_COLLECTORCATEGORIES_REQUEST";
export const CUSTOMER_COLLECTORCATEGORIES_SUCCESS =
  "CUSTOMER_COLLECTORCATEGORIES_SUCCEexport constSS";
export const CUSTOMER_COLLECTORCATEGORIES_ERROR =
  "CUSTOMER_COLLECTORCATEGORIES_ERROR";
export const CUSTOMER_WASTEGENERATAED_REQUEST =
  "CUSTOMER_WASTEGENERATAED_REQUEST";
export const CUSTOMER_WASTEGENERATAED_SUCCESS =
  "CUSTOMER_WASTEGENERATAED_SUCCESS";
export const CUSTOMER_WASTEGENERATAED_ERROR = "CUSTOMER_WASTEGENERATAED_ERROR";

//Collector Name
export const COLLECTOR_NAME_REQUEST = "COLLECTOR_NAME_REQUEST";
export const COLLECTOR_NAME_SUCCESS = "COLLECTOR_NAME_SUCCESS";
export const COLLECTOR_NAME_ERROR = "COLLECTOR_NAME_ERROR";

//Collector Profile
export const COLLECTOR_PROFILE_REQUEST = "COLLECTOR_PROFILE_REQUEST";
export const COLLECTOR_PROFILE_SUCCESS = "COLLECTOR_PROFILE_SUCCESS";
export const COLLECTOR_PROFILE_ERROR = "COLLECTOR_PROFILE_ERROR";
export const COLLECTOR_PROFILE_EDIT_REQUEST = "COLLECTOR_PROFILE_EDIT_REQUEST";
export const COLLECTOR_PROFILE_EDIT_SUCCESS = "COLLECTOR_PROFILE_EDIT_SUCCESS";
export const COLLECTOR_PROFILE_EDIT_ERROR = "COLLECTOR_PROFILE_EDIT_ERROR";

//Collector Notification count
export const COLLECTOR_NOTIFICATION_COUNT_REQUEST =
  "COLLECTOR_NOTIFICATION_COUNT_REQUEST";
export const COLLECTOR_NOTIFICATION_COUNT_SUCCESS =
  "COLLECTOR_NOTIFICATION_COUNT_SUCCES";
export const COLLECTOR_NOTIFICATION_COUNT_ERROR =
  "COLLECTOR_NOTIFICATION_COUNT_ERROR";

//Collector Notification Data
export const COLLECTOR_NOTIFICATION_DATA_REQUEST =
  "COLLECTOR_NOTIFICATION_DATA_REQUEST";
export const COLLECTOR_NOTIFICATION_DATA_SUCCESS =
  "COLLECTOR_NOTIFICATION_DATA_SUCCESS";
export const COLLECTOR_NOTIFICATION_DATA_ERROR =
  "COLLECTOR_NOTIFICATION_DATA_ERROR";

//Collector Request
export const COLLECTOR_PENDING_REQUEST = "COLLECTOR_PENDING_REQUEST";
export const COLLECTOR_PENDING_SUCCESS = "COLLECTOR_PENDING_SUCCESS";
export const COLLECTOR_PENDING_ERROR = "COLLECTOR_PENDING_ERROR";
export const COLLECTOR_PENDING_ACCEPT_REQUEST =
  "COLLECTOR_PENDING_ACCEPT_REQUEST";
export const COLLECTOR_PENDING_ACCEPT_SUCCESS =
  "COLLECTOR_PENDING_ACCEPT_SUCCESS";
export const COLLECTOR_PENDING_ACCEPT_ERROR = "COLLECTOR_PENDING_ACCEPT_ERROR";
export const COLLECTOR_SUMMARY_REQUEST = "COLLECTOR_SUMMARY_REQUEST";
export const COLLECTOR_SUMMARY_SUCCESS = "COLLECTOR_SUMMARY_SUCCESS";
export const COLLECTOR_SUMMARY_ERROR = "COLLECTOR_SUMMARY_ERROR";

//Collector E-Waste Drives
export const COLLECTOR_MYDRIVES_REQUEST = "COLLECTOR_MYDRIVES_REQUEST";
export const COLLECTOR_MYDRIVES_SUCCESS = "COLLECTOR_MYDRIVES_SUCCESS";
export const COLLECTOR_MYDRIVES_ERROR = "COLLECTOR_MYDRIVES_ERROR";
export const COLLECTOR_ORGANIZE_REQUEST = "COLLECTOR_ORGANIZE_REQUEST";
export const COLLECTOR_ORGANIZE_SUCCESS = "COLLECTOR_ORGANIZE_SUCCESS";
export const COLLECTOR_ORGANIZE_ERROR = "COLLECTOR_ORGANIZE_ERROR";
export const COLLECTOR_MYDRIVES_STATUS_REQUEST =
  "COLLECTOR_MYDRIVES_STATUS_REQUEST";
export const COLLECTOR_MYDRIVES_STATUS_SUCCESS =
  "COLLECTOR_MYDRIVES_STATUS_SUCCESS";
export const COLLECTOR_MYDRIVES_STATUS_ERROR =
  "COLLECTOR_MYDRIVES_STATUS_ERROR";

//Collector Sales
export const COLLECTOR_SOLD_REQUEST = "COLLECTOR_SOLD_REQUEST";
export const COLLECTOR_SOLD_SUCCESS = "COLLECTOR_SOLD_SUCCESS";
export const COLLECTOR_SOLD_ERROR = "COLLECTOR_SOLD_ERROR";
export const COLLECTOR_AVAILABLE_REQUEST = "COLLECTOR_AVAILABLE_REQUEST";
export const COLLECTOR_AVAILABLE_SUCCESS = "COLLECTOR_AVAILABLE_SUCCESS";
export const COLLECTOR_AVAILABLE_ERROR = "COLLECTOR_AVAILABLE_ERROR";
export const COLLECTOR_FORSALE_REQUEST = "COLLECTOR_FORSALE_REQUEST";
export const COLLECTOR_FORSALE_SUCCESS = "COLLECTOR_FORSALE_SUCCESS";
export const COLLECTOR_FORSALE_ERROR = "COLLECTOR_FORSALE_ERROR";

//Collector Analytics
export const COLLECTOR_EWASTE_DRIVES_REQUEST =
  "COLLECTOR_EWASTE_DRIVES_REQUEST";
export const COLLECTOR_EWASTE_DRIVES_SUCCESS =
  "COLLECTOR_EWASTE_DRIVES_SUCCESS";
export const COLLECTOR_EWASTE_DRIVES_ERROR = "COLLECTOR_EWASTE_DRIVES_ERROR";
export const COLLECTOR_EWASTE_ITEMS_REQUEST = "COLLECTOR_EWASTE_ITEMS_REQUEST";
export const COLLECTOR_EWASTE_ITEMS_SUCCESS = "COLLECTOR_EWASTE_ITEMS_SUCCESS";
export const COLLECTOR_EWASTE_ITEMS_ERROR = "COLLECTOR_EWASTE_ITEMS_ERROR";
export const COLLECTOR_REVENUE_CHART_REQUEST =
  "COLLECTOR_REVENUE_CHART_REQUEST";
export const COLLECTOR_REVENUE_CHART_SUCCESS =
  "COLLECTOR_REVENUE_CHART_SUCCESS";
export const COLLECTOR_REVENUE_CHART_ERROR = "COLLECTOR_REVENUE_CHART_ERROR";
export const COLLECTOR_USERS_REQUEST = "COLLECTOR_USERS_REQUEST";
export const COLLECTOR_USERS_SUCCESS = "COLLECTOR_USERS_SUCCESS";
export const COLLECTOR_USERS_ERROR = "COLLECTOR_USERS_ERROR";
export const COLLECTOR_VENDOR_REQUEST = "COLLECTOR_VENDOR_REQUEST";
export const COLLECTOR_VENDOR_SUCCESS = "COLLECTOR_VENDOR_SUCCESS";
export const COLLECTOR_VENDOR_ERROR = "COLLECTOR_VENDOR_ERROR";

//Vendor Name
export const VENDOR_NAME_REQUEST = "VENDOR_NAME_REQUEST";
export const VENDOR_NAME_SUCCESS = "VENDOR_NAME_SUCCESS";
export const VENDOR_NAME_ERROR = "VENDOR_NAME_ERROR";

//Vendor Profile
export const VENDOR_PROFILE_REQUEST = "VENDOR_PROFILE_REQUEST";
export const VENDOR_PROFILE_SUCCESS = "VENDOR_PROFILE_SUCCESS";
export const VENDOR_PROFILE_ERROR = "VENDOR_PROFILE_ERROR";
export const VENDOR_PROFILE_EDIT_REQUEST = "VENDOR_PROFILE_EDIT_REQUEST";
export const VENDOR_PROFILE_EDIT_SUCCESS = "VENDOR_PROFILE_EDIT_SUCCESS";
export const VENDOR_PROFILE_EDIT_ERROR = "VENDOR_PROFILE_EDIT_ERROR";

//Vendor Sales
export const VENDOR_VIEW_ITEMS_REQUEST = "VENDOR_VIEW_ITEMS_REQUEST";
export const VENDOR_VIEW_ITEMS_SUCCESS = "VENDOR_VIEW_ITEMS_SUCCESS";
export const VENDOR_VIEW_ITEMS_ERROR = "VENDOR_VIEW_ITEMS_ERROR";
export const VENDOR_ACCEPT_ITEMS_REQUEST = "VENDOR_ACCEPT_ITEMS_REQUEST";
export const VENDOR_ACCEPT_ITEMS_SUCCESS = "VENDOR_ACCEPT_ITEMS_SUCCESS";
export const VENDOR_ACCEPT_ITEMS_ERROR = "VENDOR_ACCEPT_ITEMS_SUCCESS";

//Vendor MyOrders
export const VENDOR_MYORDERS_REQUEST = "VENDOR_MYORDERS_REQUEST";
export const VENDOR_MYORDERS_SUCCESS = "VENDOR_MYORDERS_SUCCESS";
export const VENDOR_MYORDERS_ERROR = "VENDOR_MYORDERS_ERROR";

//Vendor Analytics
export const VENDOR_CATGITEMS_REQUEST = "VENDOR_CATGITEMS_REQUEST";
export const VENDOR_CATGITEMS_SUCCESS = "VENDOR_CATGITEMS_SUCCESS";
export const VENDOR_CATGITEMS_ERROR = "VENDOR_CATGITEMS_ERROR";
export const VENDOR_CATEGORY_REQUEST = "VENDOR_CATEGORY_REQUEST";
export const VENDOR_CATEGORY_SUCCESS = "VENDOR_CATEGORY_SUCCESS";
export const VENDOR_CATEGORY_ERROR = "VENDOR_CATEGORY_ERROR";
export const VENDOR_COLLECTOR_DATA_REQUEST = "VENDOR_COLLECTOR_DATA_REQUEST";
export const VENDOR_COLLECTOR_DATA_SUCCESS = "VENDOR_COLLECTOR_DATA_SUCCESS";
export const VENDOR_COLLECTOR_DATA_ERROR = "VENDOR_COLLECTOR_DATA_ERROR";
export const VENDOR_VENDOR_DATA_REQUEST = "VENDOR_VENDOR_DATA_REQUEST";
export const VENDOR_VENDOR_DATA_SUCCESS = "VENDOR_VENDOR_DATA_SUCCESS";
export const VENDOR_VENDOR_DATA_ERROR = "VENDOR_VENDOR_DATA_ERROR";

//Profile's PopUp
export const COLLECTOR_CUSTOMERPROFILE_REQUEST =
  "COLLECTOR_CUSTOMERPROFILE_REQUEST";
export const COLLECTOR_CUSTOMERPROFILE_SUCCESS =
  "COLLECTOR_CUSTOMERPROFILE_SUCCESS";
export const COLLECTOR_CUSTOMERPROFILE_ERROR =
  "COLLECTOR_CUSTOMERPROFILE_ERROR";
export const CUSTOMER_COLLECTORPROFILE_REQUEST =
  "CUSTOMER_COLLECTORPROFILE_REQUEST";
export const CUSTOMER_COLLECTORPROFILE_SUCCESS =
  "CUSTOMER_COLLECTORPROFILE_SUCCESS";
export const CUSTOMER_COLLECTORPROFILE_ERROR =
  "CUSTOMER_COLLECTORPROFILE_ERROR";
export const VENDOR_COLLECTORPROFILE_REQUEST =
  "VENDOR_COLLECTORPROFILE_REQUEST";
export const VENDOR_COLLECTORPROFILE_SUCCESS =
  "VENDOR_COLLECTORPROFILE_SUCCESS";
export const VENDOR_COLLECTORPROFILE_ERROR = "VENDOR_COLLECTORPROFILE_ERROR";
export const VENDOR_COLLECTORPROFILE_ACCEPT_REQUEST =
  "VENDOR_COLLECTORPROFILE_ACCEPT_REQUEST";
export const VENDOR_COLLECTORPROFILE_ACCEPT_SUCCESS =
  "VENDOR_COLLECTORPROFILE_ACCEPT_SUCCESS";
export const VENDOR_COLLECTORPROFILE_ACCEPT_ERROR =
  "VENDOR_COLLECTORPROFILE_ACCEPT_ERROR";
