//SignIn
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCSS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

//SignUp
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

//ForgotPassword
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

//ResetPassword
export const RESET_PASSWORD_REQUEST = "REQUEST_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "REQUEST_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "REQUEST_PASSWORD_ERROR";
