//SignIn
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCSS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

//SignUp
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

//ForgotPassword
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

//ResetPassword
export const RESET_PASSWORD_REQUEST = "REQUEST_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "REQUEST_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "REQUEST_PASSWORD_ERROR";

//Customer Name
export const CUSTOMER_NAME_REQUEST = "CUSTOMER_NAME_REQUEST";
export const CUSTOMER_NAME_SUCCESS = "CUSTOMER_NAME_SUCCESS";
export const CUSTOMER_NAME_ERROR = "CUSTOMER_NAME_ERROR";

//Customer Profile
export const CUSTOMER_PROFILE_REQUEST = "CUSTOMER_PROFILE_REQUEST";
export const CUSTOMER_PROFILE_SUCCESS = "CUSTOMER_PROFILE_SUCCESS";
export const CUSTOMER_PROFILE_ERROR = "CUSTOMER_PROFILE_ERROR";

//Customer Notification Count
export const CUSTOMER_NOTIFICATION_COUNT_REQUEST =
  "CUSTOMER_NOTIFICATION_COUNT_REQUEST";
export const CUSTOMER_NOTIFICATION_COUNT_SUCCESS =
  "CUSTOMER_NOTIFICATION_COUNT_SUCCESS";
export const CUSTOMER_NOTIFICATION_COUNT_ERROR =
  "CUSTOMER_NOTIFICATION_COUNT_ERROR";

//Customer Notification Data
export const CUSTOMER_NOTIFICATION_DATA_REQUEST =
  "CUSTOMER_NOTIFICATION_DATA_REQUEST";
export const CUSTOMER_NOTIFICATION_DATA_SUCCESS =
  "CUSTOMER_NOTIFICATION_DATA_SUCCESS";
export const CUSTOMER_NOTIFICATION_DATA_ERROR =
  "CUSTOMER_NOTIFICATION_DATA_ERROR";

//Collector Name
export const COLLECTOR_NAME_REQUEST = "COLLECTOR_NAME_REQUEST";
export const COLLECTOR_NAME_SUCCESS = "COLLECTOR_NAME_SUCCESS";
export const COLLECTOR_NAME_ERROR = "COLLECTOR_NAME_ERROR";

//Collector Profile
export const COLLECTOR_PROFILE_REQUEST = "COLLECTOR_PROFILE_REQUEST";
export const COLLECTOR_PROFILE_SUCCESS = "COLLECTOR_PROFILE_SUCCESS";
export const COLLECTOR_PROFILE_ERROR = "COLLECTOR_PROFILE_ERROR";

//Collector Notification count
export const COLLECTOR_NOTIFICATION_COUNT_REQUEST =
  "COLLECTOR_NOTIFICATION_COUNT_REQUEST";
export const COLLECTOR_NOTIFICATION_COUNT_SUCCESS =
  "COLLECTOR_NOTIFICATION_COUNT_SUCCES";
export const COLLECTOR_NOTIFICATION_COUNT_ERROR =
  "COLLECTOR_NOTIFICATION_COUNT_ERROR";

//Collector Notification Data
export const COLLECTOR_NOTIFICATION_DATA_REQUEST =
  "COLLECTOR_NOTIFICATION_DATA_REQUEST";
export const COLLECTOR_NOTIFICATION_DATA_SUCCESS =
  "COLLECTOR_NOTIFICATION_DATA_SUCCESS";
export const COLLECTOR_NOTIFICATION_DATA_ERROR =
  "COLLECTOR_NOTIFICATION_DATA_ERROR";

//Vendor Name
export const VENDOR_NAME_REQUEST = "VENDOR_NAME_REQUEST";
export const VENDOR_NAME_SUCCESS = "VENDOR_NAME_SUCCESS";
export const VENDOR_NAME_ERROR = "VENDOR_NAME_ERROR";

//Vendor Profile
export const VENDOR_PROFILE_REQUEST = "VENDOR_PROFILE_REQUEST";
export const VENDOR_PROFILE_SUCCESS = "VENDOR_PROFILE_SUCCESS";
export const VENDOR_PROFILE_ERROR = "VENDOR_PROFILE_ERROR";
